### ISSUE TITLE
Processing in Maven

### ISSUE THREAD

**Issue by poqudrof** [ruby-processing/processing-core#1]
Hello, 

I proposed myself to publish processing in Maven, I did no know you also did it. I asked in the Processing github to know if it was OK to publish it officially, and they were OK. 

So if you want to have a look at the discussion: 

https://github.com/processing/processing/issues/3109

It is on maven central, you just need to add this to download core :  

``` xml
  <dependency>
    <groupId>org.processing</groupId>
      <artifactId>core</artifactId>
      <version>2.2.1</version>
    </dependency>
```

http://search.maven.org/#search%7Cga%7C1%7Corg.processing

**Comment by monkstone** [comment]
That's excellent, I'm concentrating on ruby-processing-3.0 (proposed as JRubyArt), but we could provide a completely independent ruby-processing as a maven build (including jruby) which would be kind of neat. At the moment the existing version works OK, and has the advantage of piggy-backing on the processing-ide (mainly for downloads of contributed libraries, and for documentation).
I have had the odd run in with Ben Fry, so I never took it further. Anyway looks a though this repo is redundant and we should provide links to maven central instead.
